name: pre-commit linter and formatter
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build:
    name: "Syntax Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.head_ref}}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.2.8"
# Enable once env is configured     - run: pip config --user set global.index-url https://${{ secrets.ARTIFACTORY_USER_NAME }}:${{ secrets.ARTIFACTORY_KEY }}@${{ secrets.ARTIFACTORY_URL }}
      - run: python -m pip install pre-commit==2.20.0
      - run: python -m pip freeze --local
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: "Run pre-commit on branch contents"
        continue-on-error: true
        run: pre-commit run --all-files --source ${{ github.event.pull_request.base.sha }} --origin ${{ github.event.pull_request.head.sha }} --show-diff-on-failure
#      - run: |
#          echo "::set-output name=fixed::$(git diff --name-only --fix-filter=ACMRT ${{ github.event.pull}})"
      - name: "Commit any changes"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -u
          git diff --staged --quiet || git commit -m "pre-commit made changes to your branch. Please confirm the changes before merging." && git push
#          git diff-index --quiet HEAD -- || git push
