name: Terraform Autoformatting

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

#env:
#  PROJECT_ID: ""


jobs:
  terraform-pr-fmt:
    name: Autoformatting .tf files
    runs-on: ubuntu-latest
#    environment: production

#    permissions:
#      contents: 'read'
#      pull-requests: 'write'
#      id-token: 'write'

    steps:
    - name: Checkout
#      env:
#        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        ref: ${{github.event.pull_request.head}}
#      run: gh pr checkout ${{ github.event.pull_request.number }}

    - name: Get changes
      run: |
        for f in $(git diff --name-only -r ${{ github.base_ref }} HEAD | xargs); \
        terraform fmt $f; done

#    - name: Format
#      run: 

    - name: Push changes
      run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
